spring:
  security:
    user:
      name: admin
      password: 123456
server:
  port: 5721
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka #http://130.75.131.241:8761/eureka,http://130.75.131.248:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5 #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}